%% Projeto filtros FIR
% José Joseilton dos Santos Souza - 118111104
% No arquivo  sinal.wav  foi gravado um sinal composto de soma de cossenos 
% amostrados a uma frequência de 16 kHz. Deseja-se conhecer quantas  
% componentes (cossenos) formam esse sinal;
% Também foi solicitado um sistema que separe as componentes do sinal gravado.
clc;
clear all;
close all;

format short

Fs  = 48e3;
N   = 2;
Q1   = 2;
Q2   = 6;
G1   = 3; % 9 dB
G2   = 4; % 9 dB
Wo1 = 2000/(Fs/2);
Wo2 = 20000/(Fs/2);
BW1 = Wo1/Q1;
BW2 = Wo2/Q2;
[B1,A1] = designParamEQ(N,G1,Wo1,BW1,'Orientation','row');
[B2,A2] = designParamEQ(N,G2,Wo2,BW2,'Orientation','row');
BQ1 = dsp.SOSFilter('Numerator',B1,'Denominator',A1);
BQ2 = dsp.SOSFilter('Numerator',B2,'Denominator',A2);
hfvt = fvtool(BQ1,BQ2,'Fs',Fs,'Color','white');
legend(hfvt,'BW1 = 200 Hz; Q = 10','BW2 = 2000 Hz; Q = 10');


frameSize = 64;
inFs      = 96e3;

source = dsp.Chirp(InitialFrequency=0,TargetFrequency=48e3, ...
    SweepTime=8,TargetTime=8,SampleRate=inFs, ...
    SamplesPerFrame=frameSize,Type="Quadratic");

SpectrumAnalyzer44p1 = spectrumAnalyzer( ...
    SampleRate=44100, ...
    Method="welch", ...
    AveragingMethod="exponential", ...
    ForgettingFactor=1e-7, ...
    ViewType="spectrum-and-spectrogram", ...
    TimeSpanSource="property",TimeSpan=8, ...
    Window="kaiser",SidelobeAttenuation=220, ...
    YLimits=[-250, 50],ColorLimits=[-150, 20], ...
    PlotAsTwoSidedSpectrum=false);

SpectrumAnalyzer96 = spectrumAnalyzer( ...
    SampleRate=96000, ...
    Method="welch", ...
    AveragingMethod="exponential", ...
    ForgettingFactor=1e-7, ...
    ViewType="spectrum-and-spectrogram", ...
    TimeSpanSource="property",TimeSpan=8, ...
    Window="kaiser",SidelobeAttenuation=220, ...
    YLimits=[-250, 50],ColorLimits=[-150, 20], ...
    PlotAsTwoSidedSpectrum=false);